language: java
jdk:
- oraclejdk8
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  bucket_name: elasticbeanstalk-eu-central-1-887663466140
  zip_file: target/ROOT.war.original
  access_key_id: AKIAJBH2Q4N74TWYJMTA
  secret_access_key:
    secure: wryZkWT8/qduZB8wMhbGXHI0Irj+7nKFJsg5Wg/l1t+OVJjio+JeVGC137uoujCzPdbd3Kb06ssXdUFyHyMTbqJTG1AFaPn6venLJELeRJohQPPwSjLcuQjrNXt7gC9czWT0Au8bCTZpu0F6D93zx8byeguaBltulOvci5By2q8hzCnaUeiGBM9mqJR6LMIr+rICrHhgPi9qc/mJ4UhlSjHWdZ7sBvTOJejxJrNzwJXksOHGqXmIJ/c93BysrNa9INHnzG1+rSIiyhY24+y1yFzMmxQebUysfukYYmWWxjVD6KRzDwZC66IvOTIcB0AP/o9c/I8KTWJCMmKBXjfSFwQEcJ5iTHyPxWlnUSd68EQcfoJUilJg+5C4KTrP9P25cIhEdZd5gonHIGMjQeLtGPZat6ilNI+eDIDNSf7fMWTgCWBGYAIz1pEpwa3LloJYrBDchhyOVrNVqL/MwfbX0mFMH0kgIy3PhMnbADvhaIIUJqP2PxeEtC6U5s4xGIOFYmWsq3F6tDCWxfK1K6kThvXOonalmBjgNmFG+wB0blDPYBNgk/2e66bpbYGCO0jG7MM6u7D6w1apZb+EhoIdVSQs2Jx7x2tECMQiszghx7hl2YTNj2Fk5bAlVepV2R0US5ljk48Ypi7P7rJT3gR20YRg91nG3XzrvKlh1AXH0CI=
  region: eu-central-1
  app: walls.de
  env: Wallsde-env
  on:
    repo: debueb/pro-padel
    branch: aws
