language: java
jdk:
- oraclejdk8
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  bucket_name: elasticbeanstalk-eu-central-1-887663466140
  zip_file: target/ROOT.war.original
  access_key_id: AKIAJBH2Q4N74TWYJMTA
  secret_access_key:
    secure: m9V+7zgOIZbzFGWD7KjiuGTAG6E838lbmEEa4qyWOtPocL/JUPphz07vEO9VgIeZxq5n3cFSURUM/lAPH1TbxDchqz8J14Ywrsa5JqGGmfpQqq6w/puNG9WN8mzvYc7C8fVg8TQlIFIVq/ajYprN6AL7fzx26CXyHpNP5k/Cl6yOXlOSIBSTQ6vk4P7TylMaA4boFA4MSqHI7Xmmum5YPdLawJNtao6HQYKPV/agD9sEF5TTqQ6Kfead4Bl7ktkxaGzebWEqGAg5ReOapxHnJslWMBTra96ELOQQcW9FTBDpgUOj9F09G7nDLAAdtmx9j5artozRKVBb5NkPb/o5q7lcEW4pChPXjR3IDHeZPkO4PpPcYjn7lygowqyQT5a7fZckeQEvsuBZBQgxLp1//E9/mkuOQfeg+DyZ3fCd8wp0bHi2TRZFVITpGUpKU1UtP6TuwTORuN8X7UNOYjP8+Dczc0kk6h8PdAYMtunpollQYt3MmQQntJznjFUDYNXrr4+y338dsjTrwUhPkDa5Zu2zo19jrKO5b4TTCzYr1Xa/JnQrtAMEfR+al/OUGeLhnJC0aA19kGHQLFgV4mv36i8PDBztmK1PGrnSy4n8EUFyZ47rwDikM6P/xt5m/FypPwPuR5NUzgMmqbYETCyLFyUEsT597dCOHatOkwd9aRQ=
  region: eu-central-1
  app: walls.de
  env: Wallsde-env
  on:
    repo: debueb/pro-padel
    branch: master
